### ISSUE TITLE
import tobii_research is not working 

### ISSUE THREAD

**Issue by getReema** [tobiipro/prosdk-addons-python#3]
Hello, 
I've tried to use tobii_research, but the pip install available on https://pypi.org/project/tobii-research/ is not working.
I've tried both pip & pip3 as in the capture:

<img width="638" alt="Screen Shot 2020-12-15 at 9 18 35 PM" src="https://user-images.githubusercontent.com/49389693/102255742-8603e080-3f1b-11eb-96dd-d1ef9ffa42d6.png">

**Comment by grebdems** [comment]
Hi,
Looks like you're running python version(s) for which there is no support in tobii_research. 
You can check at the bottom left of the pypi page which python versions are supported (currently 2.7 & 3.5).

/Magnus

**Comment by getReema** [comment]
Before, I have tried to install while specifying the version number, I've tried all the versions on the PyPi, none worked with me.

Today as you specified, I've changed the compiler to python 2.7 (you can see it in the right corner) but still getting error as in the capture.
<img width="821" alt="Screen Shot 2020-12-16 at 10 14 44 PM" src="https://user-images.githubusercontent.com/49389693/102395995-e7e04b00-3fec-11eb-8b54-327ff1d81f90.png">

**Comment by grebdems** [comment]
Hi,
I'm not familiar with what tool you're using, so I cannot say for sure that changing the python version in it (your bottom-right corner) actually changes what version pip uses from the terminal. 
If you run `pip --version` you should see both the version of pip, as well as what version of python that pip is using.

The error from pip is pretty blunt, and only indicates that there are no matching versions of the module you're trying to install, and the environment you're running. It would help if you could share what environment you're using. I see that you're on a Mac, what version of macOS? 

/Magnus
